// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rbac.project.Repoistorys;

namespace Rbac.project.WebAPI.Migrations
{
    [DbContext(typeof(RbacDbContext))]
    partial class RbacDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rbac.project.Domain.Power", b =>
                {
                    b.Property<int>("PowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MegDeleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MegUpdateTipme")
                        .HasColumnType("datetime2");

                    b.Property<string>("MesgCreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MsgCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MsgDeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MsgUpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PowerTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PowerId");

                    b.ToTable("Power");
                });

            modelBuilder.Entity("Rbac.project.Domain.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MegDeleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MegUpdateTipme")
                        .HasColumnType("datetime2");

                    b.Property<string>("MesgCreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MsgCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MsgDeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MsgUpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RoleCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Rbac.project.Domain.RolePower", b =>
                {
                    b.Property<int>("RolePowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PowerID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("RolePowerId");

                    b.ToTable("RolePower");
                });

            modelBuilder.Entity("Rbac.project.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MegDeleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MegUpdateTipme")
                        .HasColumnType("datetime2");

                    b.Property<string>("MesgCreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MsgCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MsgDeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MsgUpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPwaword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Rbac.project.Domain.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
